# Generated by Django 5.2.8 on 2025-11-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='start_time',
        ),
    ]
