# Generated by Django 5.2.5 on 2025-09-04 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_course_enrollment_instructor_students_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
