# Generated by Django 5.2.5 on 2025-09-09 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_students_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
